apiVersion: v1
kind: Service
metadata:
  name: crematory-software
  namespace: cs
  labels:
    name: crematory-software
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: crematory-software
  type: LoadBalancer